controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

doctrine.orm.default_metadata_driver:
    resource: ../src/Entity/
    type: annotation

#users_register:
#    path: /api/users/add
#    methods: ['POST']
#    defaults:
#        _controller: App\Controller\UserController::registerUser
#        _api_resource_class: App\Entity\User
#        _api_collection_operation_name: register_user
# config/routes.yaml
api_login_check:
    path: /api/login_check
