controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

doctrine.orm.default_metadata_driver:
    resource: ../src/Entity/
    type: annotation
